base: &base
  adapter: mysql2
  host: localhost
  user: root
  password: 
  pool: 20
  timeout: 5000
  reconnect: true
  wait_timeout: 5

development: 
  <<: *base
  database: kwisatz_development

test: &test
  <<: *base
  database: kwisatz_test

cucumber:
  <<: *test
