:Question:
    :Basic:
        :problem:
            String
        :solution:
            String
        :categories:
            Array
    :Blockbuster:
        :letter:
            String
:Round:
    :Basic:
        :question_count:
            Integer
        :categories:
            Array
      